import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{Heart,RefreshCw,Volume2,VolumeX,Maximize2,Search,Home,Flame,Compass,Clock,Bookmark,Settings,Monitor,Smartphone,Play,Pause,ChevronUp,ChevronDown}from'lucide-react';import'./style.css';
const CATS=[['recommend','推荐'],['hot','热门'],['dance','热舞'],['fashion','穿搭'],['scenery','风景'],['anime','动漫'],['handsome','帅哥'],['random','随机']];
const nav=[['推荐',Home],['热门',Flame],['发现',Compass],['历史',Clock],['收藏',Bookmark],['设置',Settings]];
function safeArr(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}
function App(){const[age,setAge]=useState(localStorage.ev18==='yes');const[cat,setCat]=useState('recommend');const[video,setVideo]=useState(null);const[next,setNext]=useState(null);const[loading,setLoading]=useState(false);const[muted,setMuted]=useState(localStorage.evMuted!=='no');const[liked,setLiked]=useState(false);const[theater,setTheater]=useState(false);const[mode,setMode]=useState('single');const[history,setHistory]=useState(safeArr('evHistory'));const videoRef=useRef(null);const wheelLock=useRef(false);
const load=async(target=cat,swap=false)=>{setLoading(true);try{const r=await fetch(`/api/video?category=${target}&t=${Date.now()}`);const d=await r.json();if(!d.ok)throw Error(d.message);const item={...d,ts:Date.now(),likes:Math.floor(600+Math.random()*98000),views:(Math.random()*90+10).toFixed(1)+'万'};if(swap)setNext(item);else{setVideo(item);setLiked(false);const h=[item,...history].slice(0,30);setHistory(h);localStorage.evHistory=JSON.stringify(h)}}catch(e){setVideo(v=>v||{title:'接口连接失败，点击换一批重试',url:'',category:target,views:'0',likes:0,error:e.message})}finally{setLoading(false)}};
useEffect(()=>{if(age){load(cat);setTimeout(()=>load(cat,true),600)}},[age,cat]);
useEffect(()=>{localStorage.evMuted=muted?'yes':'no';if(videoRef.current)videoRef.current.muted=muted},[muted]);
const goNext=()=>{if(next){setVideo(next);const h=[next,...history].slice(0,30);setHistory(h);localStorage.evHistory=JSON.stringify(h);setNext(null);setTimeout(()=>load(cat,true),200)}else load(cat)};
const goPrev=()=>{if(history[1])setVideo(history[1])};
useEffect(()=>{const key=e=>{if(e.key==='ArrowDown')goNext();if(e.key==='ArrowUp')goPrev();if(e.code==='Space'){e.preventDefault();const v=videoRef.current;if(v)v.paused?v.play():v.pause()}if(e.key==='m')setMuted(x=>!x);if(e.key==='f')document.querySelector('.playerShell')?.requestFullscreen?.()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[next,history,cat]);
const onWheel=e=>{if(innerWidth<760)return;if(wheelLock.current)return;wheelLock.current=true;setTimeout(()=>wheelLock.current=false,650);e.deltaY>0?goNext():goPrev()};
if(!age)return <AgeGate onOk={()=>{localStorage.ev18='yes';setAge(true)}}/>;
return <main className={`app ${theater?'theater':''}`} onWheel={onWheel}><div className="bg">{video?.url&&<video src={video.url} muted autoPlay loop playsInline/>}<div/></div><aside className="side"><div className="brand"><b>EV</b><span>视频</span></div>{nav.map(([n,I],i)=><button className={i==0?'on':''} key={n}><I size={19}/><span>{n}</span></button>)}<div className="device"><Monitor size={16}/> PC专业版<br/><Smartphone size={16}/> 移动端自适应</div></aside><section className="main"><header className="top"><div className="search"><Search size={18}/><input placeholder="搜索分类 / 视频 / 接口" onChange={e=>{const q=e.target.value;const hit=CATS.find(x=>x[1].includes(q));if(hit)setCat(hit[0])}}/></div><div className="chips">{CATS.map(([k,n])=><button className={cat===k?'active':''} onClick={()=>setCat(k)} key={k}>{n}<small>18+</small></button>)}</div><button className="batch" onClick={()=>load(cat)}>换一批</button></header><div className="stage"><div className="playerShell"><video ref={videoRef} src={video?.url} autoPlay playsInline loop muted={muted} poster="" onClick={e=>{const v=e.currentTarget;v.paused?v.play():v.pause()}} onDoubleClick={()=>setLiked(true)} onError={()=>load(cat)} /><div className="shade"/><div className="meta"><h1>{video?.title||'EV视频加载中'}</h1><p>{video?.error||'PC端专业沉浸播放，支持滚轮切换、键盘控制、自动预加载、移动端全屏适配。'}</p><div className="stats"><span>{video?.views||'--'} 播放</span><span>{video?.likes||'--'} 喜欢</span><span>{CATS.find(x=>x[0]===cat)?.[1]}</span></div></div>{loading&&<div className="loader">EV Loading...</div>}<div className="actions"><button className={liked?'liked':''} onClick={()=>setLiked(!liked)}><Heart fill={liked?'currentColor':'none'}/></button><button onClick={goNext}><RefreshCw/></button><button onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Volume2/>}</button><button onClick={()=>setTheater(!theater)}><Maximize2/></button></div><div className="arrows"><button onClick={goPrev}><ChevronUp/></button><button onClick={goNext}><ChevronDown/></button></div></div><RightPanel next={next} history={history} goNext={goNext} mode={mode} setMode={setMode}/></div></section></main>}
function AgeGate({onOk}){return <div className="gate"><div className="gateCard"><div className="logo">EV</div><h1>EV视频</h1><p>成人向短视频聚合演示站。进入前请确认你已年满18岁，并遵守当地法律法规。</p><button onClick={onOk}>我已满18岁，进入</button><small>Vercel Serverless · YuJn API Proxy · PC/Mobile Ready</small></div></div>}
function RightPanel({next,history,goNext,mode,setMode}){return <aside className="right"><div className="panel"><h3>下一条预加载</h3>{next?<div className="preview" onClick={goNext}><video src={next.url} muted playsInline/><b>{next.title}</b><span>点击立即播放</span></div>:<div className="skeleton"/>}</div><div className="panel"><h3>播放模式</h3><div className="seg"><button className={mode==='single'?'active':''} onClick={()=>setMode('single')}>沉浸</button><button className={mode==='grid'?'active':''} onClick={()=>setMode('grid')}>瀑布</button></div><p className="tips">滚轮/↑↓切换，空格暂停，M静音，F全屏。</p></div><div className="panel"><h3>观看历史</h3>{history.slice(0,5).map((x,i)=><div className="hist" key={i}><span>{i+1}</span><b>{x.title}</b><small>{x.views}</small></div>)}</div></aside>}
createRoot(document.getElementById('root')).render(<App/>);
